config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'products/new'

  get 'products/index'

  get 'home/index'

  get 'home/index' => "home#index"
  root :to => 'home#index'
  
  resources :products
  get 'products' => "products#index"
  get 'products/new' => "products#new"
  post 'products/new' => 'products#create'
  get 'products/show'=> 'products#show'
  post '/products/:id/edit(.:format)' => 'products#edit'
  get 'login' => 'users#login'
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
    validates(:name, presence: true)
    validates(:email, presence: true)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index 
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
  end
  
  def index
    @products = Product.all
  end
  
  def create
   @product = Product.new(product_params)
  if @product.save
    redirect_to @product
  else
    render 'new'
  end
  end
  
  def show
    @product=Product.find(params[:id])
  end
  
  def edit
      @product = Product.find(params[:id])
  end
  
  def update
     @product=Product.find(params[:id])
      if @product.update_attributes(product_params)
      # Handle a successful update.
      redirect_to @product
      else
      render 'edit'
      end
  end
  
  def destroy
    Product.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to products_url
  end
  
  def kind(number)
    sNumber_to_kind = {"1" => "Book", "2" => "Item", "3" => "furniture"}
    return sNumber_to_kind[number.to_s]
  end
  
  def product_params
      params.require(:product).permit(:name, :description, :kind,
                                   :imagesrc)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/productsnew_helper.rb
module ProductsnewHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="container">
<div class="jumbotron">
  <h1>Brown Antiques and Books</h1>
  <p>Welcome to Brown Antiques and Books, your one stop shop for all things old.</p>
  <p><%= button_to "Learn More", products_path, {method: 'get', class: "btn btn-primary btn-lg"}%></p>
</div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6"> 
            <h1 class="text-center">View Our Products</h1>
            <div class="panel panel-default">
                <div class="panel-body">
        
                    <br/>
                    <p>
                        Our products are of the highest quality. We pride ourselves on finding the finest antiques goods.
                    </p>
                    <br/>
                    <%= button_to "Products", products_path, {method: 'get', class: "btn btn-primary"} %>
                </div>
            </div>
        </div>
        
        <div class="col-md-6"> 
            <h1 class="text-center">Placeholder</h1>
            <div class="panel panel-default">
                <div class="panel-body">
        
                    <br/>
                    <p>
                        Lorem ipsum!
                    </p>
                    <br/>
                    <%= button_to "Products", products_path, :class => "btn btn-primary" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
   <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Cinzel">
          <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Trirong">
    <style>
      h1, h2, h3, h4, h5, h6, a, input{
        font-family: 'Cinzel', serif;
      }
      p, input{
        font-family: 'Trirong';
        font-size: medium;
      }
    </style>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.google.com/specimen/Pinyon+Script?selection.family=Pinyon+Script" rel="stylesheet" type="text/css" />
</head>
<body>
  <div class="container">
  <nav class="navbar navbar-default">
      <a class="navbar-brand" href="/home/index">Brown Antiques</a>
      <ul class="nav navbar-nav">
        <li class="nav-item <%= 'active' if current_page?(home_index_path) %>">
          <a class="nav-link" href="/home/index">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item <%= 'active' if current_page?(products_path) %>">
          <a class="nav-link" href="/products">For Sale</a>
        </li>
        <li class="nav-item <%= 'active' if current_page?(root_path) %>">
          <a class="nav-link" href="http://v4-alpha.getbootstrap.com/examples/jumbotron/#">Contact</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <li><a href="/login">Login</a></li>
      <li><a href="/users/new">Create an Account</a></li>
    </ul>
    </nav>
  </div>
<%= yield %>

</body>

</html>

app/views/products/edit.html.erb
<div class='container'>
    <h1>Edit Product</h1>
    <div class='col-md-8' >
   <div class="panel panel-default">
    <div class="panel-body">
    <%=form_for @product, :html => {:class => "form-horizontal center"} do |p| %>
        <div class="form-group">
        
            <%= p.label :name, "Name:", class: "col-md-4 control-label"  %>
            <div class="col-xs-4">
                <%= p.text_field :name, class: "form-control" %>
            </div>
        </div>
         <div class="form-group">
            <%= p.label :description, "Description:", class: "col-md-4 control-label"  %>
            <div class="col-xs-4">
                <%= p.text_area :description, class: "form-control" %>
            </div>
        </div>
        <div class="form-group">
        
            <%= p.label :imagesrc, "Image Source:", class: "col-md-4 control-label"  %>
            <div class="col-xs-4">
                <%= p.text_field :imagesrc, class: "form-control" %>
            </div>
            <br/>
            <br/>
            <br/>
            <div class="form-group">
        
            <%= p.label :kind, "Product Type:", class: "col-md-4 control-label"  %>
            <div class="col-xs-4">
            <%= p.select(:kind, options_for_select([['Book'], ['Item'],['Furniture']], 'Book'), {}, {:class => "selectpicker form-control"})%>

            </div>
            <br/>
             
        </div>
       
        <%= p.submit 'Submit', :class => "btn btn-primary form-horizontal center" %>
        </div>
        
    <% end %>
  </div>
</div>

</div>
</div>

app/views/products/index.html.erb
<div class="container">
</div>
<div class="container">
    <div class="row">
        <!--Create Items -->
        <div class="col-md-9">
            
            <% @products.each_with_index do |p,i| %>
            <div class="panel panel-default">
                <div class="panel-body">
                <div>
                    <img src='<%= p.imagesrc %>' style='max-width: 200px; max-height: 200px;'/>
                    <h2><%= p.name %></h2>
                    <p><%= p.description %></p>
                    <div class='row'>
                        <div class='col-xs-1'>
                            <%= button_to "View", product_path(p), {method: 'get', class: "btn btn-primary"} %>
                        </div>
                        <div class='col-xs-1'>
                            <%= button_to "Edit", edit_product_path(p), :class => "btn btn-primary" %>
                        </div>
                        <div class='col-xs-1'>
                            <%= button_to "Delete", product_path(p), method: :delete,
                                  data: { confirm: "Are you sure you want to delete this product?" }, :class => "btn btn-primary" %>
                        </div>
                    </div>
                    </div>
                    </div>
                </div>
            <% end %>
        </div>
        <!--Sidebar-->
         <div class="col-xs-6 col-sm-3 sidebar-offcanvas">
            <div class='panel panel-default'>
                <div class="panel-body">
                    <a href='/products/new'>Add a new Product</a>
                </div>
            </div>
         </div>
    </div>
</div>

app/views/products/new.html.erb
<div class='container'>
    <h1>Add a Product</h1>
    <div class='col-md-8' >
   <div class="panel panel-default">
    <div class="panel-body">
    <%=form_for :product, :html => {:class => "form-horizontal center"} do |p| %>
        <div class="form-group">
        
            <%= p.label :name, "Name:", class: "col-md-4 control-label"  %>
            <div class="col-xs-4">
                <%= p.text_field :name, class: "form-control" %>
            </div>
        </div>
         <div class="form-group">
            <%= p.label :description, "Description:", class: "col-md-4 control-label"  %>
            <div class="col-xs-4">
                <%= p.text_area :description, class: "form-control" %>
            </div>
        </div>
        <div class="form-group">
        
            <%= p.label :imagesrc, "Image Source:", class: "col-md-4 control-label"  %>
            <div class="col-xs-4">
                <%= p.text_field :imagesrc, class: "form-control" %>
            </div>
            <br/>
            <br/>
            <br/>
            <div class="form-group">
        
            <%= p.label :kind, "Product Type:", class: "col-md-4 control-label"  %>
            <div class="col-xs-4">
            <%= p.select(:kind, options_for_select([['Book'], ['Item'],['Furniture']], 'Book'), {}, {:class => "selectpicker form-control"})%>

            </div>
            <br/>
             
        </div>
       
        
        </div>
        <div class="form-group">
        
            
            <div class="col-xs-4">
             <%= p.submit 'Submit', :class => "btn btn-primary form-horizontal center" %>

            </div>
            <br/>
             
        </div>
       
    <% end %>
  </div>
</div>

</div>
</div>

app/views/products/show.html.erb
<div class='container'>
    <h1><%=@product.name %></h1>
   <div class="panel panel-default">
    <div class="panel-body">
        <h2>Description</h2>
        <%=@product.description%>
        <h2>Type</h2>
        <%=@product.kind%>
  </div>
</div>

</div>
    

app/views/users/login.html.erb
<div class='container'>
    <h1>Login</h1>
    <div class='col-xs-4' >
   <div class="panel panel-default">
    <div class="panel-body">
    <%=form_for :product, :html => {:class => "form-horizontal center"} do |p| %>
        <div class="form-group">
        
            <%= p.label :username, "Username:", class: "col-md-4 control-label"  %>
            <div class="col-md-8">
                <%= p.text_field :username, class: "form-control" %>
            </div>
        </div>
         <div class="form-group">
            <%= p.label :password, "Password:", class: "col-md-4 control-label"  %>
            <div class="col-md-8">
                <%= p.text_field :password, type: "password", class: "form-control" %>
            </div>
        </div>
        
        <div class="form-group pull-right">
        
            
            <div class="col-xs-4">
             <%= p.submit 'Submit', :class => "btn btn-primary form-horizontal center" %>

            </div>
            <br/>
             
        </div>
    <% end %>
    <p>Not a User? <a href='/users/new'>Create an account</a></p>
  </div>
</div>

</div>
</div>

app/views/users/new.html.erb
<div class='container'>
    <h1>New User</h1>
    <div class='col-md-8' >
   <div class="panel panel-default">
    <div class="panel-body">
    <%=form_for :product, :html => {:class => "form-horizontal center"} do |p| %>
        <div class="form-group">
        
            <%= p.label :name, "Name:", class: "col-md-4 control-label"  %>
            <div class="col-xs-4">
                <%= p.text_field :name, class: "form-control" %>
            </div>
        </div>
         <div class="form-group">
            <%= p.label :email, "Email Address:", class: "col-md-4 control-label"  %>
            <div class="col-xs-4">
                <%= p.text_field :email, class: "form-control" %>
            </div>
        </div>
        <div class="form-group">
            <%= p.label :password, "Password:", class: "col-md-4 control-label"  %>
            <div class="col-xs-4">
                <%= p.text_field :password, class: "form-control" %>
            </div>
        </div>
        <div class="form-group">
            <%= p.label :confirmpassword, "Confirm Password:", class: "col-md-4 control-label"  %>
            <div class="col-xs-4">
                <%= p.text_field :confirmpassword, class: "form-control" %>
            </div>
        </div>
        <div class="form-group center">
        
            
            <div class="col-xs-4 center">
             <%= p.submit 'Submit', :class => "btn btn-primary form-horizontal center" %>

            </div>
            <br/>
             
        </div>
       
    <% end %>
  </div>
</div>

</div>
</div>